config/routes.rb
KoreanReferenceManual::Application.routes.draw do
  
  resources :example_sentences

  resources :flashcards

  resources :words

  resources :grammar
  
  root :to => 'grammar#index'
  

end

app/models/example_sentence.rb
class ExampleSentence < ActiveRecord::Base
  attr_accessible :english, :korean, :example_sentence_id
  
  validates :korean, :presence => true
  validates :english, :presence => true
  
  has_many :example_sentence_words
  has_many :words, :through => :example_sentence_words
end

app/models/example_sentence_word.rb
class ExampleSentenceWord < ActiveRecord::Base
  attr_accessible :example_sentence_id, :word_id
  
  belongs_to :example_sentence
  belongs_to :word
end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
  attr_accessible :level, :user, :word, :studied_dates, :word_id
  
  belongs_to :user
  belongs_to :word
  has_many :studied_dates
    
  def due
    
  end
  
  def times_studied
    
  end
end

app/models/studied_date.rb
class StudiedDate < ActiveRecord::Base
  attr_accessible :date, :flashcard
  
  belongs_to :flashcard
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :word
  
  attr_accessible :english
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  
  has_many :flashcards, :dependent => :destroy
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :korean, :flashcard, :example_sentence,
                  :word_id 
  
  validates :korean, :presence => true
  
  has_many :example_sentence_words
  has_many :example_sentences, :through => :example_sentence_words
  has_many :flashcards
  has_many :translations
  
  def has_example_sentences?
    example_sentences.count != 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'verb'
  
  protect_from_forgery
  
  before_filter :set_locale
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/example_sentences_controller.rb
class ExampleSentencesController < ApplicationController
  # GET /example_sentences
  # GET /example_sentences.json
  def index
    @example_sentences = ExampleSentence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @example_sentences }
    end
  end

  # GET /example_sentences/1
  # GET /example_sentences/1.json
  def show
    @example_sentence = ExampleSentence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @example_sentence }
    end
  end

  # GET /example_sentences/new
  # GET /example_sentences/new.json
  def new
    @example_sentence = ExampleSentence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @example_sentence }
    end
  end

  # GET /example_sentences/1/edit
  def edit
    @example_sentence = ExampleSentence.find(params[:id])
  end

  # POST /example_sentences
  # POST /example_sentences.json
  def create
    @example_sentence = ExampleSentence.new(params[:example_sentence])

    respond_to do |format|
      if @example_sentence.save
        format.html { redirect_to @example_sentence, notice: 'Example sentence was successfully created.' }
        format.json { render json: @example_sentence, status: :created, location: @example_sentence }
      else
        format.html { render action: "new" }
        format.json { render json: @example_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /example_sentences/1
  # PUT /example_sentences/1.json
  def update
    @example_sentence = ExampleSentence.find(params[:id])

    respond_to do |format|
      if @example_sentence.update_attributes(params[:example_sentence])
        format.html { redirect_to @example_sentence, notice: 'Example sentence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @example_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /example_sentences/1
  # DELETE /example_sentences/1.json
  def destroy
    @example_sentence = ExampleSentence.find(params[:id])
    @example_sentence.destroy

    respond_to do |format|
      format.html { redirect_to example_sentences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    user = User.first
    @flashcards = user.flashcards
    @flashcard = user.flashcards.first
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flashcards }
    end
  end

  def show
    @flashcard = Flashcard.due

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flashcard }
    end
  end

  def correct
    flashcard = Flashcard.find(params[:id])
    if flashcard.level < 5
      flashcard.level = flashcard.level + 1
    end
    redirect_to @flashcard, notice: 'Right!'
  end
  
  def wrong
    flashcard = Flashcard.find(params[:id])
    if flashcard.level > 1
      flashcard.level = flashcard.level - 1
    end
    redirect_to @flashcard, notice: 'Wrong!'
  end

  def new
    user = User.first
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(params[:flashcard])

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully created.' }
        format.json { render json: @flashcard, status: :created, location: @flashcard }
      else
        format.html { render action: "new" }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flashcard = Flashcard.find(params[:id])
    @flashcard.destroy

    respond_to do |format|
      format.html { redirect_to flashcards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/grammar_controller.rb
#!/bin/env ruby
# encoding: utf-8

class GrammarController < ApplicationController
  
  
  class Adjective
    def initialize(adjective)
      @adjective = adjective
    end
  end
  
  def index
    @title = t(:title)
    
    @verb = Verb.new("하다")
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/example_sentences_helper.rb
module ExampleSentencesHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/example_sentences/_form.html.erb
<%= form_for(@example_sentence) do |f| %>
  <% if @example_sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example_sentence.errors.count, "error") %> prohibited this example_sentence from being saved:</h2>

      <ul>
      <% @example_sentence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :korean %><br />
    <%= f.text_field :korean %>
  </div>
  <div class="field">
    <%= f.label :english %><br />
    <%= f.text_field :english %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/example_sentences/edit.html.erb
<h1>Editing example_sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @example_sentence %> |
<%= link_to 'Back', example_sentences_path %>

app/views/example_sentences/index.html.erb
<h1>Listing example_sentences</h1>

<table>
  <tr>
    <th>Korean</th>
    <th>English</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @example_sentences.each do |example_sentence| %>
  <tr>
    <td><%= example_sentence.korean %></td>
    <td><%= example_sentence.english %></td>
    <td><%= link_to 'Show', example_sentence %></td>
    <td><%= link_to 'Edit', edit_example_sentence_path(example_sentence) %></td>
    <td><%= link_to 'Destroy', example_sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Example sentence', new_example_sentence_path %>

app/views/example_sentences/new.html.erb
<h1>New example_sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', example_sentences_path %>

app/views/example_sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Korean:</b>
  <%= @example_sentence.korean %>
</p>

<p>
  <b>English:</b>
  <%= @example_sentence.english %>
</p>


<%= link_to 'Edit', edit_example_sentence_path(@example_sentence) %> |
<%= link_to 'Back', example_sentences_path %>

app/views/flashcards/_card.html.erb
<section class="card-container span-4">
  <div id="card">
    <figure class="front">
			<div class="korean">
				<span class="word"><%= @flashcard.word.korean %></span>
			</div>
		</figure>
    <figure class="back">
			<div class="back-text">
				<div class="original-word">
					<div class="word"><%= @flashcard.word.korean %></div>
					<div class="level"><span class="badge badge-warning"><%= @flashcard.level %></span></div>
					<div  class="pronunciation">hangukeo</div>
				</div>
				<div class="translations">
					<div class="header">Translation:</div>
					<% @flashcard.word.translations.each do |translation| %>
					<div class="translation"><%= translation.english %></div>
					<% end %>
				</div>
				<% if @flashcard.word.has_example_sentences? %>
				<div class="example-sentences">
					<div class="header">
						Example sentences:
					</div>
					<% @flashcard.word.example_sentences.each do |example_sentence| %>
					<div class="example-sentence">
						<%= example_sentence.korean %></br>
						<%= example_sentence.english %>
					</div>
					<% end %>
				</div>
				<% end %>
			</div>
			<div class="button-group">
				<button class="button" id="wrong">Wrong</button>
				<button class="button" id="correct">Correct</button>
				<button class="button">○</button>
			</div>
		</figure>
  </div>
</section>

app/views/flashcards/_form.html.erb
<%= form_for(@flashcard) do |f| %>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flashcards/edit.html.erb
<h1>Editing flashcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @flashcard %> |
<%= link_to 'Back', flashcards_path %>

app/views/flashcards/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2><%=t :flashcards%></h2>
		<p><%=t :flashcard_description%></p>
	</div>
</div>
<div class="row-fluid">
	<div class="span4">
		<%= render "card", :flashcard => @flashcard %>
	</div>
	<div class="span8">
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th>Korean</th>
					<th>English</th>
					<th>Level</th>
					<th>Sentence</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @flashcards.each do |flashcard| %>
				<tr>
					<td><%= flashcard.word.korean %></td>
					<td><%= flashcard.word.translations.first.english %></td>
					<td><%= flashcard.level %></td>
					<td><%= 
					if flashcard.word.example_sentences.first
						flashcard.word.example_sentences.first.korean
					end %></td>
					<td><%= link_to 'Show', flashcard %></td>
					<td><%= link_to 'Edit', edit_flashcard_path(flashcard) %></td>
					<td><%= link_to 'Destroy', flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
				<% end %>
			<tbody>
		</table>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<p>This is the foundation, enjoy</p>
	</div>
</div>
<%= render "grammar/this" %>

app/views/flashcards/new.html.erb
<h1>New flashcard</h1>

<%= render 'form' %>

<%= link_to 'Back', flashcards_path %>

app/views/flashcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @flashcard.user %>
</p>

<p>
  <b>Word:</b>
  <%= @flashcard.word %>
</p>

<p>
  <b>Level:</b>
  <%= @flashcard.level %>
</p>


<%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
<%= link_to 'Back', flashcards_path %>

app/views/grammar/_adjectives.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2>形容詞</h2>
		<p>Adjectives and other noise</p>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th></th>
					<th>する</th>
					<th>しない</th>
					<th>した</th>
					<th>したい</th>
					<th>しよう</th>
					<th>してる</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>普通</th>
					<td>하다</td>
					<td>했다 (했어)</td>
					<td>하지않다 (안하다)</td>
					<td>하자</td>
					<td>하고싶어</td>
					<td>하고있어</td>
				</tr>
				<tr>
					<th>敬語</th>
					<td>합니다</td>
					<td>했습니다</td>
					<td></td>
					<td></td>
					<td></td>
					<td>하고있습니다</td>
				</tr>
			</tbody>
		</table>
		<p>This is the foundation, enjoy</p>
	</div>
</div>

app/views/grammar/_hangul.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2><%=t :hangul_title %></h2>
		<p></p>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th>자음</th>
					<th colspan="13">Consonants</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ㄱ</td>
					<td>ㄴ</td>
					<td>ㄷ</td>
					<td>ㄹ</td>
					<td>ㅂ</td>
					<td>ㅅ</td>
					<td>ㅇ</td>
					<td>ㅈ</td>
					<td>ㅎ</td>
					<td>ㅋ</td>
					<td>ㅌ</td>
					<td>ㅍ</td>
					<td>ㅊ</td>
					<td>ㅁ</td>
				</tr>
				<tr>
					<td>k/g</td>
					<td>n</td>
					<td>d/t</td>
					<td>r/l</td>
					<td>b/p</td>
					<td>s</td>
					<td>ng</td>
					<td>j/ch</td>
					<td>h</td>
					<td>k</td>
					<td>t</td>
					<td>p</td>
					<td>ch</td>
					<td>m</td>
				</tr>
			</tbody>
			<thead>
				<tr>
					<th>모음</th>
					<th colspan="13">Vowels</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ㅣ</td>
					<td>ㅏ</td>
					<td>ㅑ</td> 
					<td>ㅓ</td> 
					<td>ㅕ</td> 
					<td>ㅐ</td>
					<td>ㅔ</td>
					<td colspan="4"></td>
					<td>ㅟ</td>
					<td>ㅢ</td>
					<td>ㅚ</td>
				</tr> 
				<tr>
					<td>i</td> 
					<td>a</td>
					<td>ya</td>
					<td>eo</td>
					<td>yeo</td>
					<td>ae</td>
					<td>e</td>
					<td colspan="4"></td> 
					<td>wi</td>
					<td>ui</td>
					<td>wa</td>	
				</tr> 
				<tr>
					<td>ㅡ</td>
					<td>ㅗ</td> 
					<td>ㅛ</td> 
					<td>ㅜ</td> 
					<td>ㅠ</td> 
					<td colspan="6"></td>
					<td>ㅝ</td>
					<td>ㅙ</td>
					<td>ㅞ</td>
				</tr>
				<tr>
					<td>eu</td>
					<td>o</td>
					<td>yo</td>
					<td>u</td>
					<td>yu</td>
					<td colspan="6"></td> 
					<td>wo</td>
					<td>wae</td>
					<td>we</td>
				</tr> 
			</tbody>
		</table>
		<p>This table consist of all them cool hangul.</p>
	</div>
</div>

app/views/grammar/_particles.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2><%=t :partcle_title%></h2>
		<p><%=t :partcle_description%></p>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th colspan="7">Particles</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>은/는</td>
					<td>이/가</td>
					<td>을/를</td>
					<td>으로/로</td>
					<td>까지</td>
					<td>에</td>
					<td>하고/와/과</td>
				</tr>
				<tr>
					<td>は</td>
					<td>が</td>
					<td>を</td>
					<td>で</td>
					<td>まで</td>
					<td>へ</td>
					<td>と</td>
				</tr>
				<tr>
					<td>의/것</td>
					<td>도/이나/나</td>
					<td>에/에게</td>
					<td>부터</td>
					<td>에서</td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td>の</td>
					<td>も</td>
					<td>に</td>
					<td>から</td>
					<td>から/で</td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
		<p>This is the foundation, enjoy</p>
	</div>
</div>

app/views/grammar/_this.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2><%=t :partcle_title%></h2>
		<p><%=t :partcle_description%></p>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th></th>
					<th>Things</th>
					<th></th>
					<th>Place</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>This</th>
					<td>이</td>
					<td>이거</td>
					<td>여기</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<th>That</th>
					<td>그</td>
					<td>그거</td>
					<td>거기</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<th>That (over there)</th>
					<td>저</td>
					<td>저거</td>
					<td>저기</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<th>What</th>
					<td>어느</td>
					<td>어느 거</td>
					<td>어디</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
		<p>This is the foundation, enjoy</p>
	</div>
</div>

app/views/grammar/_verbs.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2><%=t :verb_title%></h2>
		<p><%=t :verb_description%></p>
		<ul class="nav nav-tabs" id="myTab">
		  <li class="active"><a href="#conjugations">Conjugations</a></li>
		  <li><a href="#honorific">Honorific</a></li>
			<li><a href="#home">Conjugations</a></li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane active" id="conjugations">
				<table class="table table-hover table-condensed">
					<thead>
						<tr>
							<th></th>
							<th>Plain</th>
							<th>Informal</th>
							<th>Polite</th>
							<th>Formal</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>Present</th>
							<td><%= @verb.present.plain %></td>
							<td><%= @verb.present.informal %></td>
							<td><%= @verb.present.polite %></td>
							<td><%= @verb.present.formal %></td>
						</tr>
						<tr>
							<th>Past</th>
							<td><%= @verb.past.plain %></td>
							<td><%= @verb.past.informal %></td>
							<td><%= @verb.past.polite %></td>
							<td><%= @verb.past.formal %></td>
						</tr>
						<tr>
							<th>Future</th>
							<td><%= @verb.future.plain %></td>
							<td><%= @verb.future.informal %></td>
							<td><%= @verb.future.polite %></td>
							<td><%= @verb.future.formal %></td>
						</tr>
					</tbody>
					<thead>
						<tr>
							<th></th>
							<th>Plain</th>
							<th>Informal</th>
							<th>Polite</th>
							<th>Formal</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>propositive</th>
							<td><%= @verb.propositive.plain %></td>
							<td><%= @verb.propositive.informal %></td>
							<td><%= @verb.propositive.polite %></td>
							<td><%= @verb.propositive.formal %></td>
						</tr>
						<tr>
							<th>Imperative</th>
							<td><%= @verb.imperative.plain %></td>
							<td><%= @verb.imperative.informal %></td>
							<td><%= @verb.imperative.polite %></td>
							<td><%= @verb.imperative.formal %></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="tab-pane" id="honorific">
				<table class="table table-hover table-condensed">
					<thead>
						<tr>
							<th></th>
							<th>Plain</th>
							<th>Informal</th>
							<th>Polite</th>
							<th>Formal</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>Present</th>
							<td><%= @verb.present.honorific.plain %></td>
							<td><%= @verb.present.honorific.informal %></td>
							<td><%= @verb.present.honorific.polite %></td>
							<td><%= @verb.present.honorific.formal %></td>
						</tr>
						<tr>
							<th>Past</th>
							<td><%= @verb.past.honorific.plain %></td>
							<td><%= @verb.past.honorific.informal %></td>
							<td><%= @verb.past.honorific.polite %></td>
							<td><%= @verb.past.honorific.formal %></td>
						</tr>
						<tr>
							<th>Future</th>
							<td><%= @verb.future.honorific.plain %></td>
							<td><%= @verb.future.honorific.informal %></td>
							<td><%= @verb.future.honorific.polite %></td>
							<td><%= @verb.future.honorific.formal %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<p><%=t :verb_table_caption%><%= @verb.connective %></p>
	</div>
</div>

app/views/grammar/index.html.erb
<%= render "hangul" %>
<%= render "verbs" %>
<%= render "particles" %>
<%= render "vocabulary/numbers" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Korean Reference Manual</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag "stylesheet", :media => "all" %>
	<%= stylesheet_link_tag "flashcards", :media => "all" %>
	<%= stylesheet_link_tag "bootstrap", :media => "all" %>
	<%= stylesheet_link_tag "bootstrap-responsive", :media => "all" %>
	
	<%= javascript_include_tag "application" %>
</head>
<body>
	
<%= render "shared/menu" %>

<div class="container">
	<%= render "shared/header" %>
	<%= yield %>
</div>
<%= render "shared/footer" %>
</body>
</html>

app/views/pages/about.html.erb
<div id="content-border">
	<div id="static-border">
	<div id="static-head">
		<h1><%= t :about %></h1>
	</div>
	<div id="static-mid">
		<div class="column-onethird">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed viverra nunc. Integer accumsan neque in lectus interdum vulputate. Nulla vel libero eu elit placerat fringilla. Cras lobortis lacus in tellus adipiscing pretium. Fusce ligula nunc, commodo eu sagittis vel, aliquam consequat nisi. Suspendisse potenti. Etiam aliquam tempor lacinia. Ut suscipit nulla ut neque condimentum accumsan. Morbi sed ante est. <br /><br />Nulla magna est, hendrerit sed auctor interdum, gravida at velit. Suspendisse viverra vestibulum condimentum. Cras dui lectus, ullamcorper in fermentum tincidunt, pulvinar eget nunc. Praesent interdum lacus dictum diam lobortis non congue dui scelerisque. Donec imperdiet pharetra elit, ac porttitor turpis faucibus dictum. In lectus magna, gravida id accumsan eu, molestie a nibh. Sed hendrerit commodo posuere. Nulla facilisi.
		</div>
		<div class="column-onethird-italic">
			Nullam felis orci, semper in consectetur non, rutrum at est. Sed justo lorem, aliquam nec accumsan eget, tempus at enim.
		</div>
		<div class="column-onethird-headline">
			Praesent vehicula
		</div>
		<div class="column-onethird">
			Praesent vehicula aliquam lacus eleifend adipiscing. Sed et orci at tellus pulvinar congue. Vivamus elementum placerat massa ac dignissim. Mauris ut dolor arcu. Suspendisse dolor diam, interdum eget sodales eget, consectetur in odio. Donec vitae nulla ut elit tempus tristique. Aenean dictum tincidunt turpis, nec mattis ante sodales eu.
		</div>
	</div>	
	<div id="static-tail">
	</div>	
</div>
</div>

app/views/shared/_menu.html.erb
<header></header>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Korean</th>
    <th>English</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.korean %></td>
    <td><%= word.english %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Korean:</b>
  <%= @word.korean %>
</p>

<p>
  <b>English:</b>
  <%= @word.english %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>